### PR TITLE
Add "RangerCurrentFile" command

### PR DESCRIPTION
**Pull request by yaegassy**
## Description

I'm currently using [ranger.vim](https://github.com/francoiscabrol/ranger.vim).

ranger.vim has `:RangerCurrentFile` command.

This command uses the `--choosefile` to specify the "current file".

I use `:RangerCurrentFile` a lot.

Since `ranger-explorer.vim` doesn't have similar functionality, we've added `:RangerOpenCurrentFile`.

## Demo

ranger-explorer-pr

### CODE REVIEW

**Comment by iberianpig** [comment]
The feature of this PR doesn't work on My Environment.

```
$ ranger --version
ranger version: ranger 1.9.3
Python version: 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
Locale: None.None
```



[Image from Gyazo](https://gyazo.com/3c677ac6f0aa27b0d5698141b9dfb51f)

I got the following errors.
```
ranger version: ranger 1.9.3
Python version: 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
Locale: None.None

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/ui.py", line 334, in redraw
    self.finalize()
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/ui.py", line 391, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/displayable.py", line 268, in finalize
    displayable.finalize()
  File "/usr/local/lib/python2.7/dist-packages/ranger/gui/widgets/view_base.py", line 60, in finalize
    - self.main_column.scroll_begin
AttributeError: 'NoneType' object has no attribute 'pointer'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

**Comment by yaegassy** [comment]
@iberianpig Thank you for checking it out.

I'm using the latest (`master`) version of ranger's "GitHub" repository.

**My Enviroment:**

```
$ # Creating a virtual environment with venv
$ python3 -m venv ~/.local/src/ranger/venv

$ # Specify the ranger repository in the virtual environment pip and install
$ ~/.local/src/ranger/venv/bin/pip3 install -U git+https://github.com/ranger/ranger

$ # Put a symbolic link on the PATH.
$ ln -snf ~/.local/src/ranger/venv/bin/ranger ~/.local/bin/ranger

$ ranger --version
ranger version: ranger-master
Python version: 3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27) [Clang 6.0 (clang-600.0.57)]
Locale: ja_JP.UTF-8
```

I have investigated the error.

Unfortunately, this problem seems to occur in `v1.9.3` and `v1.9.2`. :(

Ref: https://github.com/ranger/ranger/issues/1655

When `v1.9.4` is "officially released", it should work fine, but we will close this PR once. :(

**Comment by yaegassy** [comment]
## Change command arguments if path is file

@iberianpig hi, 

Changed to specify in `--selectfile` option if the path is a file.

This should work fine in `v1.9.3` and `v1.9.2`.

I tried it on Mac, Ubuntu, and Fedora and it orked fine.

- pip: v1.9.3 and v1.9.2
- Ubuntu(apt): v1.9.3
- Fedora(dnf): v1.9.2

Try it out when you have the time!

**Comment by iberianpig** [comment]
Sorry for the long wait :bow:

The bug has been fixed in this commit.
`:RangerOpenCurrentFile` is working fine. :100: 

Thanks for your contribution.
